### PR TITLE
Fix usability issues in CLI, add missing features.

### PR DESCRIPTION
**Pull request by dmach**

### CODE REVIEW

**Comment by lubomir** [comment]
The test are failing because they call a script that no longer exists. The `.travis.yml` file should be updated.

**Comment by hluk** [comment]
@dmach Not sure how much time are you willing to spend on this PR.

We are thinking of cherry-picking separate commits from here, solving conflicts, creating PR request for each JIRA and fixing any further problems. Do you think this would be OK?

**Comment by xiangge** [comment]
@dmach I agree with @hluk , we want to separate these commits.

**Comment by hluk** [comment]
Everything should be merged now except ["Use local plugins..."](https://github.com/product-definition-center/pdc-client/pull/91/commits/64bea69836fd4bdaa321753e1438c44d609a4e81) commit was replaced with f0b60a3.

**Pull request closed without merging**
