### PR TITLE
Sort commands in pdc --help

### PR DESCRIPTION
**Pull request by simozhan**
JIRA: PDC-2059

### CODE REVIEW

**Comment by hluk** [comment]
Tests seems to fail with Python 3.x because [relative imports are no longer allowed](https://wiki.python.org/moin/PortingPythonToPy3k#relative-imports). So instead of `import compat` it should be `from pdc_client import compat`.

**Comment by hluk** [comment]
Actually, that's problem when I run tests with Python 3.6. Travis tests give different error.

**Comment by hluk** [comment]
OK, nevermind. Using `from pdc_client import compat` seems to fix the error for Python 3.4 too. Though the error is very cryptic. :)

**Comment by simozhan** [comment]
@hluk cool. thank you very much :)

**Comment by xiangge** [comment]
Looks good to me.

**Review by hluk — CHANGES_REQUESTED** [review]
I would prefer if you leave the original commit untouched -- mainly the author should be the same. I.e. cherry-pick/rebase the original commit and add another commits for the fixes.

**Comment by simozhan** [comment]
@hluk ok. fix it.

**Review by xiangge — APPROVED** [review]

**Review by hluk — APPROVED** [review]

**Pull request merged**
