### PR TITLE
Update the SPEC file for removing the directories.

### PR DESCRIPTION
**Pull request by bliuredhat**
JIRA: PDC-1654

### CODE REVIEW

**Comment by ycheng-aa** [comment]
Looks good.

It already has the line `%dir %{_sysconfdir}/pdc.d` in the spec file. Why does the Jira mention `.....and /etc/pdc.d directories are still existed.` ? Is it a problem?

**Comment by bliuredhat** [comment]
@ycheng-aa , For internal SPEC file in gerrit, it miss the %dir %{_sysconfdir}/pdc.d line.

**Comment by ycheng-aa** [comment]
Understood. Thanks.

**Comment by simozhan** [comment]
:+1:

**Pull request merged**
