### PR TITLE
Fix pdc client release clone.

### PR DESCRIPTION
**Pull request by xychu**
Make '--include-trees' args to form a list.
JIRA: PDC-1149

### CODE REVIEW

**Comment by lubomir** [comment]
This does fix the problem, but I'm not sure it is the best possible fix. The usage is `--include-trees X --include-trees Y`. This is inconsistent with how for example RPM dependencies are handled, which expect the arguments to be `--requires X Y`. I don't know which way is better, but it should be the same everywhere.

**Comment by xychu** [comment]
@lubomir forgot about the `--requires`, and I think `nargs` is better(fewer input) for user and consistent.
Have updated.

**Comment by lubomir** [comment]
:+1:

**Comment by ycheng-aa** [comment]
Looks good.

**Pull request merged**
