### PR TITLE
Add support for repo manipulation into pdc client

### PR DESCRIPTION
**Pull request by ycheng-aa**
Support GET, PATCH, CREATE, DESTROY methods
in user-friendly pdc client for content delivery
repo resource.

JIRA: PDC-1439

### CODE REVIEW

**Comment by simozhan** [comment]
Generally looks good to me. Just one thing, it seems there is no delete related test case.

**Comment by bliuredhat** [comment]
looks good for me

**Comment by ycheng-aa** [comment]
Added the test case for delete in 2bbecf3b15d538. Thanks.

**Comment by simozhan** [comment]
:+1:

**Pull request closed without merging**
