### PR TITLE
Fix failure with requests-kerberos 0.9+ and Python 3.

### PR DESCRIPTION
**Pull request by matysek**
Removing monkey_patch.py makes Python 3 working with requests-kerberos 0.8, 0.9 and 0.10. Python 2 is still failing for some reason with requests-kerberos 0.9+.

### CODE REVIEW

**Comment by ycheng-aa** [comment]
Will this patch affect pdc_client in python 2.x if the old behavior is removed?

**Comment by matysek** [comment]
@ycheng-aa no, the behavior is still same with python 2.x and kerberos-requests 0.7 and 0.8.

**Comment by ycheng-aa** [comment]
OK, then. :+1:

**Comment by simozhan** [comment]
:+1:

**Pull request merged**
