### PR TITLE
Add field 'subvariant' to image sub-command.

### PR DESCRIPTION
**Pull request by ycheng-aa**
JIRA: PDC-1521

### CODE REVIEW

**Comment by simozhan** [comment]
I tried to list an existing image, it seems no Subvariant field, does that mean Subvariant field is for future imported images

**Comment by ycheng-aa** [comment]
@simozhan  You could use --json to see full information. Without --json, it's just part of the information.

**Comment by lubomir** [comment]
The field was added only recently, and as far as I know no internal product is using it. It is used in Fedora.

**Comment by simozhan** [comment]
ok.  :+1:

**Comment by bliuredhat** [comment]
looks good for me

**Pull request merged**
