### PR TITLE
Increase `pdc content-deliver-repo list` verbosity.

### PR DESCRIPTION
**Pull request by hluk**
JIRA: PDC-1952

### CODE REVIEW

**Comment by simozhan** [comment]
It seems previous shadow is true/false, but now changed to yes/no, probably the test case failed for this.

**Comment by hluk** [comment]
Hmm, few things:
1. Is the order of columns OK?
2. The size of output table is too big.
3. Column headers are not aligned with the data.
image

**Comment by simozhan** [comment]
@hluk i think the order is not quite important and actually i think maybe ID is not very useful for the user. The size should be very long because most of the repos' name are long, not have any good idea for that.
Maybe name in a new line. Maybe we should discuss it with the users.

**Comment by xiangge** [comment]
2. The size of output table is too big.
Actually for this part, I am working on an issue about the paging, we can keep put all the data as default.
And we can give an option about the paging. 
Will commit patch for reviewing once finish.

**Comment by hluk** [comment]
@xiangge I meant that the table is too wide.

I just added commit that sets minimal column width. It might be a better idea to some library for formatting tables.

**Comment by xiangge** [comment]
@hluk ok, got that.

**Comment by hluk** [comment]
@xiangge @simozhan OK to merge this?

**Comment by simozhan** [comment]
:+1:

**Review by simozhan — APPROVED** [review]

**Review by xiangge — APPROVED** [review]
ok

**Pull request merged**
