### PR TITLE
Add Python 3 compatibility.

### PR DESCRIPTION
**Pull request by matysek**
This pull requests adds initial Python 3 compatibility. Tests passes for me with Python 2.7 and 3.4.

### CODE REVIEW

**Comment by ycheng-aa** [comment]
Looks good.

Thank you very much for the contribution.

**Comment by simozhan** [comment]
:+1:

**Comment by ycheng-aa** [comment]
@matysek Could you rebase the commits to one commit then we will merge it? Thanks.

**Comment by matysek** [comment]
@ycheng-aa done.

**Pull request merged**
