### PR TITLE
Pdc client token update

### PR DESCRIPTION
**Pull request by xiangge**
1.Change the new token/secure to chuang cao.
2.Limit the version of Sphinx to 1.2.3 to resolve the python 2.6 build failed issue.
   The root cause of this is adding new typing package dependency in latest Sphinx, 
   and even the oldest typing package can't support 2.6 build.

### CODE REVIEW

**Comment by simozhan** [comment]
Looks good to me. Please squash the two commits before merging

**Comment by simozhan** [comment]
:+1:

**Comment by hluk** [comment]
@simozhan Is there any reason to squash the two commits? It looks good to me as is.

**Comment by hluk** [comment]
👍

**Comment by simozhan** [comment]
@hluk yeah. you are right. i don't need to care about the first commit build fail. After resubmit these two commits, only the HEAD one will trigger the Travis CI build. And different features in different commits always make sense.

**Comment by xiangge** [comment]
@simozhan and @hluk , thank you very much for reviewing that. And I agree with you two.
As these two commits solve different things, I will keep them both, and also separated and modified the commit info here.
I will commit them then.

**Pull request merged**
