### PR TITLE
Update the error info

### PR DESCRIPTION
**Pull request by bliuredhat**
The pdc_client command to return "Client error: ", this patch
will remove these info

JIRA: PDC-998

### CODE REVIEW

**Comment by bliuredhat** [comment]
@lubomir, @simozhan , @ycheng-aa ; please review this patch.

**Comment by lubomir** [comment]
:+1:

**Comment by bliuredhat** [comment]
@lubomir; I consider that if we remove these code, it's bad for  code debug.

**Comment by lubomir** [comment]
I'm not sure how much help it is debugging, but we can keep. In that case there should be an `if` condition for [`SystemExit`](https://docs.python.org/2/library/exceptions.html#exceptions.SystemExit) exception and not print anything for it.

**Comment by ycheng-aa** [comment]
:+1:

**Pull request merged**
