### PR TITLE
Add help message for 'active' filter.

### PR DESCRIPTION
**Pull request by xychu**
JIRA: PDC-1219

### CODE REVIEW

**Comment by lubomir** [comment]
Alternative solution would be to have two mutually exclusive options `--active` and `--inactive`. Your solution will work too, I guess.

**Comment by xychu** [comment]
@lubomir, the `--active` and `--inactive` are my first try, it's more direct and neat.
If there is no need to make CLI backward compatible(main reason of my approach),
I'll change this to mutually exclusive options.

**Comment by lubomir** [comment]
For the CLI interface, I _think_ this change would be acceptable.

**Comment by ycheng-aa** [comment]
Looks good.

**Comment by simozhan** [comment]
:+1:

**Comment by xychu** [comment]
Changed to use mutually exclusive group(`--active` and --inactive`).

**Comment by bliuredhat** [comment]
looks good for me

**Pull request merged**
