### PR TITLE
Run tests on Python 3.5 and 3.6

### PR DESCRIPTION
**Pull request by lubomir**

### CODE REVIEW

**Comment by xiangge** [comment]
Maybe we can consider to remove the 3.3 or 3.4?

**Comment by hluk** [comment]
> Maybe we can consider to remove the 3.3 or 3.4?

Also Fedora 25 has Python 3.6 so perhaps there is no need for 3.5 either?

**Edit:** Sorry meant to say "Fedora 26 has Python 3.6".

**Comment by hluk** [comment]
"JIRA: PDC-2075" is missing in the commit message.

**Comment by lubomir** [comment]
I updated the commit message and remove 3.3. EPEL 7 has Python 3.4, so I would prefer to keep that. We currently do not build a python 3 version for EPEL, but we should.

**Review by hluk — APPROVED** [review]

**Comment by xiangge** [comment]
Cool

**Pull request merged**
